name: Test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo "Working fine"
      - name: Run chmode
        run: sudo chmod +x scripts/example.sh
      - name: Run Bash Script
        run: bash scripts/example.sh